/datum/centcom_announcer/default/lait
	welcome_sounds = list('modular_zzplurt/sound/announcer/lait/lait_welcome.ogg')
	alert_sounds = list('modular_zzplurt/sound/announcer/lait/lait_attention.ogg')
	command_report_sounds = list('modular_zzplurt/sound/announcer/lait/lait_commandreport.ogg')
	event_sounds = list(
		ANNOUNCER_ALIENS = 'modular_zzplurt/sound/announcer/lait/lait_lifesigns.ogg',
		ANNOUNCER_ANIMES = 'modular_zzplurt/sound/announcer/lait/lait_animes.ogg',
		ANNOUNCER_INTERCEPT = 'modular_zzplurt/sound/announcer/lait/lait_intercept.ogg',
		ANNOUNCER_IONSTORM = 'modular_zzplurt/sound/announcer/lait/lait_ionstorm.ogg',
		ANNOUNCER_METEORS = 'modular_zzplurt/sound/announcer/lait/lait_meteors.ogg',
		ANNOUNCER_OUTBREAK5 = 'modular_zzplurt/sound/announcer/lait/lait_outbreak5.ogg',
		ANNOUNCER_OUTBREAK7 = 'modular_zzplurt/sound/announcer/lait/lait_outbreak7.ogg',
		ANNOUNCER_POWEROFF = 'modular_zzplurt/sound/announcer/lait/lait_poweroff.ogg',
		ANNOUNCER_POWERON = 'modular_zzplurt/sound/announcer/lait/lait_poweron.ogg',
		ANNOUNCER_RADIATION = 'modular_zzplurt/sound/announcer/lait/lait_radiation.ogg',
		ANNOUNCER_SHUTTLECALLED = 'modular_zzplurt/sound/announcer/lait/lait_crew_shuttle_called.ogg',
		ANNOUNCER_SHUTTLEDOCK = 'modular_zzplurt/sound/announcer/lait/lait_crew_shuttle_docked.ogg',
		ANNOUNCER_SHUTTLERECALLED = 'modular_zzplurt/sound/announcer/lait/lait_crew_shuttle_recalled.ogg',
		ANNOUNCER_SHUTTLELEFT = 'modular_zzplurt/sound/announcer/lait/lait_crew_shuttle_left.ogg',
		ANNOUNCER_GRAVANOMALIES = 'modular_zzplurt/sound/announcer/lait/lait_gravanomalies.ogg',
		ANNOUNCER_SPANOMALIES = 'modular_zzplurt/sound/announcer/lait/lait_wormholes.ogg',
		ANNOUNCER_VORTEXANOMALIES = 'modular_zzplurt/sound/announcer/lait/lait_vortex.ogg',
		ANNOUNCER_MASSIVEBSPACEANOMALIES = 'modular_zzplurt/sound/announcer/lait/lait_bluespace_anomalies.ogg',
		ANNOUNCER_TRANSLOCATION = 'modular_zzplurt/sound/announcer/lait/lait_translocation.ogg',
		ANNOUNCER_FLUXANOMALIES = 'modular_zzplurt/sound/announcer/lait/lait_flux.ogg',
		ANNOUNCER_PYROANOMALIES = 'modular_zzplurt/sound/announcer/lait/lait_pyr_anomalies.ogg',
		ANNOUNCER_CARP = 'modular_zzplurt/sound/announcer/lait/lait_carps.ogg',
		ANNOUNCER_BLUESPACEARTY = 'modular_zzplurt/sound/announcer/lait/lait_artillery.ogg',
		ANNOUNCER_CAPTAIN = 'modular_zzplurt/sound/announcer/lait/lait_announce.ogg',
		ANNOUNCER_GRAVGENOFF = 'modular_zzplurt/sound/announcer/lait/lait_gravityoff.ogg',
		ANNOUNCER_GRAVGENON = 'modular_zzplurt/sound/announcer/lait/lait_gravityon.ogg',
		ANNOUNCER_GREYTIDE = 'modular_zzplurt/sound/announcer/lait/lait_greytide.ogg',
		ANNOUNCER_ELECTRICALSTORM = 'modular_zzplurt/sound/announcer/lait/lait_estorm.ogg',
		ANNOUNCER_BRANDINTELLIGENCE = 'modular_zzplurt/sound/announcer/lait/lait_rampant_brand_int.ogg',
		ANNOUNCER_ERTYES = 'modular_zzplurt/sound/announcer/lait/lait_yesert.ogg',
		// Fallback to default sounds for those without lait equivalents
		ANNOUNCER_AIMALF = 'sound/announcer/default/aimalf.ogg',
		ANNOUNCER_OUTBREAK6 = 'modular_skyrat/modules/alerts/sound/alerts/alert3.ogg',
		ANNOUNCER_RADIATIONPASSED = 'modular_zzplurt/sound/announcer/lait/lait_radpassed.ogg', // We need a voice line for this
		ANNOUNCER_ANOMALIES = 'modular_skyrat/modules/alerts/sound/alerts/alert2.ogg',
		ANNOUNCER_SPOOKY = 'modular_skyrat/modules/alerts/sound/misc/admin_horror_music.ogg',
		ANNOUNCER_MUTANTS = 'modular_skyrat/modules/alerts/sound/alerts/hazdet.ogg', // We could use voice lines for this
		ANNOUNCER_KLAXON = 'modular_skyrat/modules/black_mesa/sound/siren1_long.ogg',
		ANNOUNCER_ICARUS = 'modular_skyrat/modules/assault_operatives/sound/icarus_alarm.ogg',
		ANNOUNCER_NRI_RAIDERS = 'modular_skyrat/modules/encounters/sounds/morse.ogg',
		ANNOUNCER_DEPARTMENTAL = 'modular_skyrat/modules/alerts/sound/alerts/alert3.ogg',
		ANNOUNCER_SHUTTLE = 'modular_skyrat/modules/alerts/sound/alerts/alert3.ogg',
		ANNOUNCER_COMMSBLACKOUT = 'modular_skyrat/modules/alerts/sound/alerts/commsblackout.ogg',
		ANNOUNCER_GRAVGENBLACKOUT = 'modular_zzplurt/sound/announcer/lait/lait_gravityoff.ogg',
		ANNOUNCER_METEORWARNING = 'modular_zzplurt/sound/announcer/lait/lait_meteors.ogg'
	)
