/datum/centcom_announcer/intern/tibbets // GAY RAT
	welcome_sounds = list('modular_zzplurt/sound/announcer/tibbets/welcomes/01.ogg',
		'modular_zzplurt/sound/announcer/tibbets/welcomes/02.ogg',
		'modular_zzplurt/sound/announcer/tibbets/welcomes/03.ogg',
		'modular_zzplurt/sound/announcer/tibbets/welcomes/04.ogg',
		'modular_zzplurt/sound/announcer/tibbets/welcomes/05.ogg',
		'modular_zzplurt/sound/announcer/tibbets/welcomes/06.ogg')

	alert_sounds = list('modular_zzplurt/sound/announcer/tibbets/alerts/01.ogg',
		'modular_zzplurt/sound/announcer/tibbets/alerts/02.ogg',
		'modular_zzplurt/sound/announcer/tibbets/alerts/03.ogg',
		'modular_zzplurt/sound/announcer/tibbets/alerts/04.ogg',
		'modular_zzplurt/sound/announcer/tibbets/alerts/05.ogg',
		'modular_zzplurt/sound/announcer/tibbets/alerts/06.ogg',
		'modular_zzplurt/sound/announcer/tibbets/alerts/07.ogg',
		'modular_zzplurt/sound/announcer/tibbets/alerts/08.ogg',
		'modular_zzplurt/sound/announcer/tibbets/alerts/09.ogg',
		'modular_zzplurt/sound/announcer/tibbets/alerts/10.ogg',
		'modular_zzplurt/sound/announcer/tibbets/alerts/11.ogg',
		'modular_zzplurt/sound/announcer/tibbets/alerts/12.ogg',
		'modular_zzplurt/sound/announcer/tibbets/alerts/13.ogg',
		'modular_zzplurt/sound/announcer/tibbets/alerts/14.ogg',
		'modular_zzplurt/sound/announcer/tibbets/alerts/15.ogg',
		'modular_zzplurt/sound/announcer/tibbets/alerts/16.ogg',
		'modular_zzplurt/sound/announcer/tibbets/alerts/17.ogg')

	command_report_sounds = list('modular_zzplurt/sound/announcer/tibbets/commandreport/01.ogg',
		'modular_zzplurt/sound/announcer/tibbets/commandreport/02.ogg',
		'modular_zzplurt/sound/announcer/tibbets/commandreport/03.ogg',
		'modular_zzplurt/sound/announcer/tibbets/commandreport/04.ogg',
		'modular_zzplurt/sound/announcer/tibbets/commandreport/05.ogg',
		'modular_zzplurt/sound/announcer/tibbets/commandreport/06.ogg',
		'modular_zzplurt/sound/announcer/tibbets/commandreport/07.ogg',
		'modular_zzplurt/sound/announcer/tibbets/commandreport/08.ogg',
		'modular_zzplurt/sound/announcer/tibbets/commandreport/09.ogg',
		)

	event_sounds = list(
		ANNOUNCER_AIMALF = 'modular_zzplurt/sound/announcer/tibbets/aimalf.ogg',
		ANNOUNCER_ALIENS = 'modular_zzplurt/sound/announcer/tibbets/lifesigns.ogg',
		ANNOUNCER_ANIMES = 'modular_zzplurt/sound/announcer/tibbets/animes.ogg',
		ANNOUNCER_INTERCEPT = 'modular_zzplurt/sound/announcer/tibbets/alert2.ogg',
		ANNOUNCER_GRANOMALIES = 'modular_zzplurt/sound/announcer/tibbets/gravanomalies.ogg',
		ANNOUNCER_IONSTORM = 'modular_zzplurt/sound/announcer/tibbets/Ionstorm.ogg',
		ANNOUNCER_METEORS = 'modular_zzplurt/sound/announcer/tibbets/Meteors.ogg',
		ANNOUNCER_OUTBREAK5 = 'modular_zzplurt/sound/announcer/tibbets/outbreak5.ogg',
		ANNOUNCER_OUTBREAK6 = 'modular_zzplurt/sound/announcer/tibbets/alert3.ogg',
		ANNOUNCER_OUTBREAK7 = 'modular_zzplurt/sound/announcer/tibbets/outbreak7.ogg',
		ANNOUNCER_POWEROFF = 'modular_zzplurt/sound/announcer/tibbets/poweroffALT.ogg',
		ANNOUNCER_POWERON = 'modular_zzplurt/sound/announcer/tibbets/poweron.ogg',
		ANNOUNCER_RADIATION = 'modular_zzplurt/sound/announcer/tibbets/radiation.ogg',
		ANNOUNCER_RADIATIONPASSED = 'modular_zzplurt/sound/announcer/tibbets/radpassed.ogg',
		ANNOUNCER_SHUTTLECALLED = 'modular_zzplurt/sound/announcer/tibbets/crew_shuttle_called.ogg',
		ANNOUNCER_SHUTTLEDOCK = 'modular_zzplurt/sound/announcer/tibbets/crew_shuttled_docked.ogg',
		ANNOUNCER_SHUTTLERECALLED = 'modular_zzplurt/sound/announcer/tibbets/crew_shuttle_recalled.ogg',
		ANNOUNCER_SHUTTLELEFT = 'modular_zzplurt/sound/announcer/tibbets/crew_shuttle_left.ogg',
		ANNOUNCER_ANOMALIES = 'modular_zzplurt/sound/announcer/tibbets/anomaly.ogg',
		ANNOUNCER_GRAVANOMALIES = 'modular_zzplurt/sound/announcer/tibbets/gravanomalies.ogg',
		ANNOUNCER_SPANOMALIES = 'modular_zzplurt/sound/announcer/tibbets/wormholes.ogg',
		//ANNOUNCER_VORTEXANOMALIES = 'modular_skyrat/modules/alerts/sound/alerts/vortex.ogg',
		ANNOUNCER_MASSIVEBSPACEANOMALIES = 'modular_zzplurt/sound/announcer/tibbets/bluespace_anomalies.ogg',
		ANNOUNCER_TRANSLOCATION = 'modular_zzplurt/sound/announcer/tibbets/translocation.ogg',
		ANNOUNCER_FLUXANOMALIES = 'modular_zzplurt/sound/announcer/tibbets/Flux.ogg',
		ANNOUNCER_PYROANOMALIES = 'modular_zzplurt/sound/announcer/tibbets/pyr_anomalies.ogg',
		ANNOUNCER_CARP = 'modular_zzplurt/sound/announcer/tibbets/carps.ogg',
		ANNOUNCER_BLUESPACEARTY = 'modular_zzplurt/sound/announcer/tibbets/artillery.ogg',
		ANNOUNCER_CAPTAIN = 'modular_zzplurt/sound/announcer/tibbets/announce.ogg',
		ANNOUNCER_GRAVANOMALIES = 'modular_zzplurt/sound/announcer/tibbets/gravanomalies.ogg',
		ANNOUNCER_GRAVGENOFF = 'modular_zzplurt/sound/announcer/tibbets/gravityoff.ogg',
		ANNOUNCER_GRAVGENON = 'modular_zzplurt/sound/announcer/tibbets/gravityon.ogg',
		ANNOUNCER_GREYTIDE = 'modular_zzplurt/sound/announcer/tibbets/greytide.ogg',
		ANNOUNCER_COMMSBLACKOUT = 'modular_zzplurt/sound/announcer/tibbets/commsblackout.ogg',
		ANNOUNCER_ELECTRICALSTORM = 'modular_zzplurt/sound/announcer/tibbets/estorm.ogg',
		ANNOUNCER_BRANDINTELLIGENCE = 'modular_zzplurt/sound/announcer/tibbets/rampant_brand_int.ogg',
		//ANNOUNCER_SPOOKY = 'modular_skyrat/modules/alerts/sound/misc/admin_horror_music.ogg',
		ANNOUNCER_ERTYES = 'modular_zzplurt/sound/announcer/tibbets/yesert.ogg',
		//ANNOUNCER_ERTNO = 'modular_zzplurt/sound/announcer/tibbets/ertno.ogg', //what
		//ANNOUNCER_MUTANTS = 'modular_skyrat/modules/alerts/sound/alerts/hazdet.ogg',
		ANNOUNCER_ICARUS = 'modular_skyrat/modules/assault_operatives/sound/icarus_alarm.ogg',
		ANNOUNCER_NRI_RAIDERS = 'modular_skyrat/modules/encounters/sounds/morse.ogg',
		ANNOUNCER_DEPARTMENTAL = 'modular_skyrat/modules/alerts/sound/alerts/alert3.ogg',
		ANNOUNCER_SHUTTLE = 'modular_skyrat/modules/alerts/sound/alerts/alert3.ogg',
		ANNOUNCER_AURORA_CAELUS = 'modular_zzplurt/sound/announcer/tibbets/auroracaelus.ogg',
		ANNOUNCER_BUREAUCRATIC_ERROR = 'modular_zzplurt/sound/announcer/tibbets/bureaucraticerror.ogg',
		ANNOUNCER_MARKET_CRASH = 'modular_zzplurt/sound/announcer/tibbets/marketcrash.ogg',
		ANNOUNCER_MOUSE_MIGRATION = 'modular_zzplurt/sound/announcer/tibbets/mouse_migration.ogg',
		ANNOUNCER_SCRUBBER_OVERFLOW = 'modular_zzplurt/sound/announcer/tibbets/scrubberoverflow.ogg',
		ANNOUNCER_SHUTTLE_INSURANCE = 'modular_zzplurt/sound/announcer/tibbets/shuttleinsurance.ogg',
		ANNOUNCER_SUPERMATTER_SURGE = 'modular_zzplurt/sound/announcer/tibbets/supermatter_surge.ogg',
		ANNOUNCER_WISDOM_COW = 'modular_zzplurt/sound/announcer/tibbets/wisdom_cow.ogg',
		ANNOUNCER_IMMOVABLE_ROD = 'modular_zzplurt/sound/announcer/tibbets/immovablerod.ogg',
		ANNOUNCER_SCRAMBLER_ANOMALY = 'modular_zzplurt/sound/announcer/tibbets/scrambleranom.ogg'
	)

	//custom_alert_message = span_alert("Please stand by for an important message from our head rat.<br>")
	custom_alert_message = null //Make it not obfuscate the content of the announcements
